package delivery_simulator;

/**
 * Interface for objects generated by factories.
 * @author Scott Timmel
 */
public interface Simulated {

  /**
   * Operation performed by object in simulation.
   * @param task indicates how operation will be performed
   * @return Simulated
   */
  public <T> Simulated performTask(T task);
}
